// Simple JSON → TypeScript generator (handles objects, arrays, unions, optionals)
document.addEventListener('DOMContentLoaded', () => {
  const input = document.getElementById('json-input');
  const output = document.getElementById('ts-output');
  const jsonMeta = document.getElementById('json-meta');
  const tsMeta = document.getElementById('ts-meta');
  const genBtn = document.getElementById('generate-btn');
  const copyBtn = document.getElementById('copy-btn');

  function toType(value) {
    if (value === null) return 'null';
    const t = typeof value;
    if (t === 'string' || t === 'number' || t === 'boolean') return t;
    if (Array.isArray(value)) return 'array';
    if (t === 'object') return 'object';
    return 'any';
  }

  function mergeTypes(types) {
    // Merge into union string (sorted, unique)
    const unique = Array.from(new Set(types.sort()));
    return unique.join(' | ');
  }

  function pascalCase(name) {
    return String(name)
      .replace(/[^a-zA-Z0-9]+/g, ' ')
      .trim()
      .split(/\s+/)
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join('') || 'Type';
  }

  function inferArrayType(arr, contextName) {
    if (arr.length === 0) return 'any[]';
    const elementTypes = new Set();
    let mergedObjectShape = {};
    for (const el of arr) {
      const t = toType(el);
      if (t === 'object') {
        mergedObjectShape = mergeObjectShape(mergedObjectShape, el);
      }
      elementTypes.add(inferType(el, contextName + 'Item'));
    }
    if (elementTypes.size === 1) {
      const only = [...elementTypes][0];
      // If only is an interface definition, just use its name[]
      if (only.endsWith('}')) return 'any[]'; // fallback when full literal type
      return `${only}[]`;
    }
    return `(${Array.from(elementTypes).join(' | ')})[]`;
  }

  function mergeObjectShape(base, obj) {
    const result = { ...base };
    for (const key of Object.keys(obj)) {
      const value = obj[key];
      const prev = result[key];
      const currentType = toType(value);
      if (!prev) {
        result[key] = { types: new Set([currentType]), values: [value] };
      } else {
        prev.types.add(currentType);
        prev.values.push(value);
      }
    }
    return result;
  }

  function inferInterface(name, obj, defs) {
    const interfaceName = pascalCase(name);
    const lines = [`interface ${interfaceName} {`];
    for (const key of Object.keys(obj)) {
      const value = obj[key];
      const typeStr = inferType(value, pascalCase(key));
      const optional = value === null || value === undefined ? '?' : '';
      const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
      lines.push(`  ${safeKey}${optional}: ${typeStr};`);
    }
    lines.push('}');
    defs.push(lines.join('\n'));
    return interfaceName;
  }

  function inferType(value, name, defs = globalDefs) {
    const kind = toType(value);
    switch (kind) {
      case 'string':
      case 'number':
      case 'boolean':
        return kind;
      case 'null':
        return 'null';
      case 'array':
        return inferArrayType(value, name);
      case 'object':
        return inferInterface(name || 'Root', value, defs);
      default:
        return 'any';
    }
  }

  let globalDefs = [];

  function generate(jsonText) {
    globalDefs = [];
    try {
      const data = JSON.parse(jsonText);
      const rootName = Array.isArray(data) ? 'RootItem' : 'Root';
      const rootType = inferType(data, rootName);
      const header = `// Generated by JSON → TypeScript\n`;
      const defsUnique = Array.from(new Set(globalDefs)).join('\n\n');
      const result = defsUnique + (defsUnique ? '\n\n' : '') + `type ${rootName} = ${rootType};\n`;
      output.textContent = result;
      tsMeta.textContent = 'Types generated';
    } catch (e) {
      output.textContent = '';
      tsMeta.textContent = 'Invalid JSON';
    }
  }

  genBtn.addEventListener('click', () => generate(input.value));
  input.addEventListener('input', () => {
    jsonMeta.textContent = `${input.value.length} chars`;
  });
  copyBtn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(output.textContent || '');
      tsMeta.textContent = 'Copied to clipboard';
    } catch {
      tsMeta.textContent = 'Copy failed';
    }
  });
});


